name: Python CI and GCP Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: python -m unittest discover -s . -p 'test.py' -v

    - name: Set up Google Cloud SDK
      run: |
        pip install google-github-actions/auth
        gcloud auth activate-service-account --key-file=${{ secrets.GCP_SECRET }}
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

    - name: Deploy to Cloud Function
      run: |
        gcloud functions deploy test_ci_cd \
          --region=southamerica-east1 \
          --source=./ \
          --runtime=python310 \
          --entry-point=run \
          --timeout=60s \
          --trigger-http \
          --max-instances=2 \
          --service-account=sheets-credentials@charming-module-358319.iam.gserviceaccount.com \
          --allow-unauthenticated
